### ISSUE TITLE
Heeeelp installation issue

### ISSUE THREAD

**Issue by Hellomik2002** [hybridgroup/cylon-neurosky#12]
npm install cylon cylon-neurosky

> serialport@2.1.2 install C:\Users\Aliya\Desktop\neurosky-drone-master\node_modules\cylon-neurosky\node_modules\serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [
node-pre-gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'C:\\Users\\Aliya\\Desktop\\neurosky-drone-master\\node_modules\\cylon-neurosky\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build'
node-pre-gyp verb cli ]
node-pre-gyp info using node-pre-gyp@0.6.26
node-pre-gyp info using node@12.5.0 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "C:\Users\Aliya\Desktop\neurosky-drone-master\node_modules\cylon-neurosky\node_modules\serialport\build\Release\serialport.node" (not found)
node-pre-gyp http GET https://github.com/voodootikigod/node-serialport/releases/download/2.1.2/serialport-v2.1.2-node-v72-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/voodootikigod/node-serialport/releases/download/2.1.2/serialport-v2.1.2-node-v72-win32-x64.tar.gz
node-pre-gyp http Pre-built binary not available for your system, looked for https://github.com/voodootikigod/node-serialport/releases/download/2.1.2/serialport-v2.1.2-node-v72-win32-x64.tar.gz (falling back to source compile with node-gyp)
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp http Connection closed while downloading tarball file (falling back to source compile with node-gyp)
node-pre-gyp verb command build [ 'rebuild' ]

**Comment by lucastelnovo** [comment]
+1 on this... cant do npm install of the components. getting error on serialport

 ^
../src/serialport.cpp:97:44: error: no matching member function for call to 'ToObject'
  v8::Local<v8::Object> options = info[1]->ToObject();
                                  ~~~~~~~~~^~~~~~~~
/Users/lucastel/Library/Caches/node-gyp/12.18.4/include/node/v8.h:2672:44: note: candidate function not viable: requires single
      argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/lucastel/Library/Caches/node-gyp/12.18.4/include/node/v8.h:2686:31: note: candidate function not viable: requires single
      argument 'isolate', but no arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../src/serialport.cpp:109:108: error: no matching member function for call to 'ToInt32'
  baton->baudRate = Nan::Get(options, Nan::New<v8::String>("baudRate").ToLocalChecked()).ToLocalChecked()->ToInt32()->Int32Value();
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/Users/lucastel/Library/Caches/node-gyp/12.18.4/include/node/v8.h:2678:43: note: candidate function not viable: requires single
      argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Int32> ToInt32(Local<Context> context) const;
                                          ^
/Users/lucastel/Library/Caches/node-gyp/12.18.4/include/node/v8.h:2690:30: note: candidate function not viable: requires single
      argument 'isolate', but no arguments were provided
                Local<Int32> ToInt32(Isolate* isolate) const);
                             ^
../src/serialport.cpp:109:108: error: no matching member function for call to 'ToInt32'
  baton->baudRate = Nan::Get(options, Nan::New<v8::String>("baudRate").ToLocalChecked()).ToLocalChecked()->ToInt32()->Int32Value();
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/Users/lucastel/Library/Caches/node-gyp/12.18.4/include/node/v8.h:2678:43: note: candidate function not viable: requires single
      argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Int32> ToInt32(Local<Context> context) const;
                                          ^
/Users/lucastel/Library/Caches/node-gyp/12.18.4/include/node/v8.h:2690:30: note: candidate function not viable: requires single
      argument 'isolate', but no arguments were provided
fatal error: too many errors emitted, stopping now [-ferror-limit=]                Local<Int32> ToInt32(Isolate* isolate) const);

                             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
18 warnings and 20 errors generated.
18 warnings and 20 errors generated.
make: make: *** [Release/obj.target/serialport/src/serialport.o] Error 1*** [Release/obj.target/serialport/src/serialport.o] Error 1

gypgyp ERR!  build error 
ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gypgyp  ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gypERR!  ERR!stack  Error: `make` failed with exit code: 2
stack     at ChildProcess.emit (events.js:315:20)
gyp gypERR!  ERR! stackstack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! gypSystem  Darwin 15.6.0
ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/lucastel/Code/mindwave-sound/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/Users/lucastel/Code/mindwave-sound/node_modules/serialport/build/Release"
gyp ERR!gyp  commandERR! "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/lucastel/Code/mindwave-sound/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/Users/lucastel/Code/mindwave-sound/node_modules/serialport/build/Release"
 cwd /Users/lucastel/Code/mindwave-sound/node_modules/serialport
gyp gypERR!  ERR!cwd node -v /Users/lucastel/Code/mindwave-sound/node_modules/serialport
 v12.18.4
gyp gyp ERR!ERR!  node -vnode-gyp -v v5.1.0
 v12.18.4
gypgyp  ERR!ERR!  not oknode-gyp -v v5.1.0
 
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/lucastel/Code/mindwave-sound/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/Users/lucastel/Code/mindwave-sound/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/lucastel/Code/mindwave-sound/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 15.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/lucastel/Code/mindwave-sound/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/lucastel/Code/mindwave-sound/node_modules/serialport
node-pre-gyp ERR! node -v v12.18.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.26
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/lucastel/Code/mindwave-sound/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/Users/lucastel/Code/mindwave-sound/node_modules/serialport/build/Release' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@2.1.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@2.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by lucastelnovo** [comment]
Hey @Hellomik2002 ! I just could get it working with node 8
